# ZCShop 配置文件
# 格式:
# 物品名称:
#   变量: "%bank%" # 要检查的变量，例如 %bank% 表示玩家的银行余额
#   购买数字: 100 # 需要的变量值
#   超过执行的命令: "give %player% diamond 1" # 购买成功后执行的命令，%player% 会被替换为玩家名

# 示例物品
钻石:
  变量: "%bank%"
  购买数字: 100
  超过执行的命令: "give %player% diamond 1"

铁剑:
  变量: "%bank%"
  购买数字: 50
  超过执行的命令: "give %player% iron_sword 1"

金苹果:
  变量: "%bank%"
  购买数字: 200
  超过执行的命令: "give %player% golden_apple 1"